const START_OF_DOCUMENT_DATA = 'START_OF_DOCUMENT_DATA';
const END_OF_DOCUMENT_DATA = 'END_OF_DOCUMENT_DATA';
const READER_STATUS = 'READER_STATUS';

export { START_OF_DOCUMENT_DATA, END_OF_DOCUMENT_DATA, READER_STATUS };
