const START_OF_DOCUMENT_DATA = 'START_OF_DOCUMENT_DATA';
const END_OF_DOCUMENT_DATA = 'END_OF_DOCUMENT_DATA';
const READER_STATUS = 'READER_STATUS';
const IDENTITY_CARD = 'IDENTITY CARD';

export {
  START_OF_DOCUMENT_DATA,
  END_OF_DOCUMENT_DATA,
  READER_STATUS,
  IDENTITY_CARD,
};
