pipeline:
  unit_tests:
    image: quay.io/ukhomeofficedigital/node-10
    commands:
      - node -v
      - npm -v
      - npm ci
      - npm run lint
      - npm run test
    when:
      event: push
