---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/node-10
  commands:
  - node -v
  - npm -v
  - npm ci --silent
  when:
    event:
    - push

- name: unit_tests
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/node-10
  commands:
  - npm run lint
  - npm run test
  when:
    event:
    - push

services:
- name: docker
  image: docker:19.03.12-dind
  volumes:
  - name: dockersock
    path: /var/run

- name: anchore-submission-server
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  commands:
  - /anchore-submission server
  environment:
    ANCHORE_URL: acp-anchore.acp.homeoffice.gov.uk
    REGISTRY_URL: acp-ephemeral-registry.acp.homeoffice.gov.uk
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

...
