---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/node-10
  commands:
  - node -v
  - npm -v
  - npm ci --silent
  when:
    event:
    - push

- name: unit_tests
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/node-10
  commands:
  - npm run lint
  - npm run test
  when:
    event:
    - push

...
