---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: unit_tests
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/node-10
  commands:
  - node -v
  - npm -v
  - npm ci
  - npm run lint
  - npm run test
  when:
    event:
    - push

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  commands:
  - /run.sh server

...
